version: "3.9"
services:
  server:
    container_name: image-wrapper
    build:
      dockerfile: Dockerfile
    image: image-wrapper:latest
    environment:
      - DB_URL=jdbc:postgresql://image-wrapper-db:5432/postgres?user=user&password=pass
    ports:
      - "8080:8080"
    volumes:
      - .static/:/.static
    depends_on:
      - migration
    links:
      - db
  db:
    image: postgres:13.8
    container_name: image-wrapper-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgress
    restart: unless-stopped
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  migration:
    image: liquibase/liquibase
    stdin_open: true
    command: [ "sh", "/script/wait-for-postgress.sh",
               "sh", "/script/liquibase-migrate.sh"]
    volumes:
      - ./src/main/resources/changelog:/liquibase/changelog
      - ./database/script:/script
    links:
      - db
    depends_on:
      - db
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .static:/usr/share/nginx/html
